// src/components/chat/SmartChips.jsx — Follow-up question suggestions
// 2-3 pill chips shown after each assistant response. Click to send as next message.
// Escape to dismiss. Generated by a lightweight secondary LLM call (async).

import { useState, useEffect, useCallback } from 'react';

export default function SmartChips({ chips = [], onChipClick, visible = true }) {
  const [dismissed, setDismissed] = useState(false);

  // Reset dismissed state when new chips arrive
  useEffect(() => {
    if (chips.length > 0) {
      setDismissed(false);
    }
  }, [chips]);

  // Escape to dismiss
  const handleKeyDown = useCallback((e) => {
    if (e.key === 'Escape') {
      setDismissed(true);
    }
  }, []);

  useEffect(() => {
    if (visible && !dismissed && chips.length > 0) {
      document.addEventListener('keydown', handleKeyDown);
      return () => document.removeEventListener('keydown', handleKeyDown);
    }
  }, [visible, dismissed, chips.length, handleKeyDown]);

  if (!visible || dismissed || chips.length === 0) {
    return null;
  }

  return (
    <div className="flex flex-wrap items-center justify-center gap-2 py-2">
      {chips.slice(0, 3).map((chip, index) => (
        <button
          key={index}
          onClick={() => onChipClick(chip)}
          className="inline-flex items-center px-3 py-1.5 rounded-full text-xs
            border transition-all duration-150
            dark:bg-slate-800 dark:border-slate-600 dark:text-slate-300
            dark:hover:border-blue-500 dark:hover:text-blue-400 dark:hover:bg-slate-700
            bg-white border-slate-200 text-slate-600
            hover:border-blue-300 hover:text-blue-700 hover:bg-blue-50"
        >
          {chip}
        </button>
      ))}
    </div>
  );
}
